@extends('emails.layouts.luxury-dark')

@section('title', 'Your Beauty Roadmap')

@section('content')
    <h1>Your Beauty Roadmap is ready</h1>
    <p>
        Hi {{ $firstName }},<br><br>
        Thank you for completing your aesthetic evaluation with <strong>{{ $clinicName }}</strong>.
        Our AI has finished analysing your submission and your personalised Beauty Roadmap report is now ready.
    </p>

    <div class="card">
        <h3>What's in your report</h3>
        <p style="margin: 0; font-size: 14px;">
            Your Beauty Roadmap includes your AI harmony analysis result, key measurements,
            personalised insights about your {{ $procedureLabel }} consultation, answers to
            frequently asked questions relevant to your concerns, and clear next steps.
        </p>
    </div>

    <div style="text-align: center;">
        <a href="{{ $reportUrl }}" class="cta-btn" style="margin-bottom: 8px;">View Your Beauty Roadmap →</a>
        <p style="font-size: 12px; color: #9CA3AF; margin-bottom: 24px;">
            Your report is also attached to this email as a PDF.
        </p>
    </div>

    <div style="text-align: center; margin-bottom: 24px;">
        <a href="{{ url('/intake/portal/' . $secureToken) }}" class="btn-outline">
            Visit Your Patient Portal →
        </a>
    </div>

    <hr class="divider" />

    <p style="font-size: 14px;">
        A member of our team will be in touch shortly to discuss your results and schedule your consultation.
        If you have any questions in the meantime, please don't hesitate to contact us directly.
    </p>

    <p style="font-size: 14px; margin-top: 16px;">
        Warm regards,<br>
        <strong>{{ $clinicName }}</strong>
    </p>

    <hr class="divider" />

    <p style="font-size: 11px; color: #9CA3AF; line-height: 1.6;">
        This report is generated by an AI system for informational purposes only and does not constitute
        a medical diagnosis or treatment recommendation. All findings should be discussed with a qualified
        surgeon during your consultation. Individual results vary.
    </p>
@endsection

@section('footer-note')
    Powered by SymetriHealth<br>
    You received this email because you submitted an aesthetic evaluation request.
@endsection
