<?php

declare(strict_types=1);

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Photo;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Local-dev only: stream a photo from the private local disk.
 *
 * In production, SecureFileService returns S3 pre-signed URLs directly —
 * this controller is never hit. In local dev (FEATURE_AI_VISION=false),
 * photos are stored on the 'local' disk (storage/app/private/) which is
 * not web-accessible. This controller looks up a Photo by its s3_key_hash
 * (an HMAC stored in the DB), verifies tenant ownership, and streams the
 * file content so the browser can display it.
 *
 * Route:  GET /photos/{hash}  (auth + tenant middleware)
 * URL generated by: SecureFileService::getSignedUrl() in dev mode.
 */
class PhotoStreamController extends Controller
{
    public function __invoke(Request $request, string $hash): StreamedResponse|Response
    {
        /** @var Photo|null $photo */
        $photo = Photo::where('s3_key_hash', $hash)->first();

        if (!$photo) {
            abort(404);
        }

        $disk = Storage::disk('local');
        $key  = $photo->s3_key; // cast auto-decrypts

        if (!$disk->exists($key)) {
            abort(404, 'Photo file not found on disk.');
        }

        $mimeType = $this->guessMime($key);

        return response()->stream(function () use ($disk, $key): void {
            $stream = $disk->readStream($key);
            if ($stream) {
                fpassthru($stream);
                fclose($stream);
            }
        }, 200, [
            'Content-Type'  => $mimeType,
            'Cache-Control' => 'private, max-age=900', // 15 min — matches S3 signed URL expiry
        ]);
    }

    private function guessMime(string $key): string
    {
        return match (strtolower(pathinfo($key, PATHINFO_EXTENSION))) {
            'jpg', 'jpeg' => 'image/jpeg',
            'png'         => 'image/png',
            'webp'        => 'image/webp',
            'gif'         => 'image/gif',
            default       => 'application/octet-stream',
        };
    }
}
